Issue #7 : More complex filters
goldshtn/etrace pull request #8
Opened 2017-01-16 19:05 UTC by Pavel-Durov

1. Added support for unlimited All-of filters.
2. Added support for ">", "<", ">=", "<=", "!="

example:
```
etrace --kernel Proces --where "ThreadId<20000 && ProcessName=git-lfs && ParentProcessID=19496"
etrace --kernel Process --where "ThreadId>=0 && ThreadId<99 && ProcessId!=2 && StackBase>89"
etrace --kernel Process --where "ThreadId>0"

```For some reason, when using the filter without quotes - 
`etrace --kernel Process --where ThreadId>0`

won't work when lunching from CMD... 
I get this error:

> The process cannot access the file because it is being used by another process.

2017-01-17 14:09 UTC, goldshtn requested changes
Good start, there are a few changes needed before merging. Thanks.

2017-01-17 14:09 UTC, goldshtn commented on README.md
> +  etrace --kernel Process --event --where "ThreadId > 1 && ... && ProcessName=git-lfs"
I'd rather have a working example here, so please remove the `...`.

2017-01-17 14:09 UTC, goldshtn commented on README.md
> +
Why this empty line?

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +	enum ListFlags: int
What happened to the indentation here?

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +            /// <summary>
Feels a bit weird that only this method has xmldoc. I'd remove the comment, or make it a regular comment.

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +                foreach (var subFilter in SubFilters)
`return SubFilters.All(s => s.IsMatch(e));` is a bit more concise.

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +            protected Filter()
Why is this protected?

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +            /// <summary>
This is a private method, hardly any need for xmldoc.

2017-01-17 14:09 UTC, goldshtn commented on etrace/Options.cs
> +
Why this empty line?

2017-01-17 15:23 UTC, Pavel-Durov commented on etrace/Options.cs
> +            protected Filter()
So only MultipleFilter (or any other derived classes) could instantiate Filter class with default ctor

2017-01-17 16:19 UTC, Pavel-Durov commented on etrace/Options.cs
> +            /// <summary>
xmldoc removed

2017-02-09 07:04 UTC, Pavel-Durov commented on README.md
> +  etrace --kernel Process --event --where "ThreadId > 1 && ... && ProcessName=git-lfs"
changed to :   etrace --kernel Process --event --where "ThreadId > 1 && ProcessName=git-lfs"

2017-02-09 07:04 UTC, Pavel-Durov commented on README.md
> +
removed

2017-02-09 07:05 UTC, Pavel-Durov commented on etrace/Options.cs
> +	enum ListFlags: int
fixed

2017-02-09 07:05 UTC, Pavel-Durov commented on etrace/Options.cs
> +            /// <summary>
removed

2017-02-09 07:10 UTC, Pavel-Durov commented
I think I submitted all of the requested changes :)

2017-02-19 08:03 UTC, goldshtn commented
LGTM, merging.

2017-02-19 08:04 UTC, merged